#ifndef ASSEMBLER_CONSTANTS_H
#define ASSEMBLER_CONSTANTS_H


#define MAX_CODE_LINE 81
#define WORD_SIZE 11
#define COMMENT_CHAR ';'
#define LABEL_SEPARATOR ':'
#define BLANK_CHARACTER_SEPERATOR " \t\n\r"
#define DECIMAL_BASE 10

#endif
